spring:
  application:
    name: recommender
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4o-mini
  cache:
    type: caffeine
    cache-names: musicRecommendations, oldMusicRecommendations
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m
  mvc:
    static-path-pattern: /static/**
server:
  port: 8080
  error:
    whitelabel:
      enabled: false  # Disable the default ugly Whitelabel page
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /
